const BUYER_EMAIL="REPLACE_WITH_YOUR_YOUNG_GENTLEMAN_EMAIL";
const products=[
["midnight-polo","Midnight Signature Polo","Polos","₹1,000–₹2,000"],["forest-club-polo","Forest Club Polo","Polos","₹1,000–₹2,000"],["sage-pinstripe-polo","Sage Pinstripe Polo","Polos","₹1,000–₹2,000"],["black-essential-polo","Black Essential Polo","Polos","₹500–₹1,000"],["white-crest-polo","White Crest Polo","Polos","₹1,000–₹2,000"],["burgundy-texture-polo","Burgundy Heritage Polo","Statement","₹1,000–₹2,000"],["peach-monogram-polo","Peach Monogram Polo","T-Shirts","₹1,000–₹2,000"],["royal-check-polo","Royal Check Polo","Polos","₹1,000–₹2,000"],["mustard-club-polo","Mustard Club Polo","Polos","₹500–₹1,000"],["ivory-contrast-polo","Ivory Contrast Polo","Polos","₹1,000–₹2,000"],["charcoal-essential-polo","Charcoal Essential Polo","Polos","₹500–₹1,000"],["grey-yg-tee","Grey YG Signature Tee","T-Shirts","₹500–₹1,000"],["sky-stripe-polo","Sky Stripe Polo","Statement","₹1,000–₹2,000"],["slate-knit-polo","Slate Knit Polo","Polos","₹1,000–₹2,000"],["rose-monogram-polo","Rose Monogram Polo","T-Shirts","₹1,000–₹2,000"],["heritage-burgundy-polo","Heritage Burgundy Polo","Statement","₹1,000–₹2,000"],["contrast-shoulder-polo","Ivory Shoulder Detail Polo","Statement","₹1,000–₹2,000"],["deep-black-polo","Deep Black Signature Polo","Polos","₹500–₹1,000"]];
const grid=document.getElementById("productGrid"),modal=document.getElementById("productModal"),modalImage=document.getElementById("modalImage"),modalTitle=document.getElementById("modalTitle"),modalCategory=document.getElementById("modalCategory"),modalPrice=document.getElementById("modalPrice");
function renderProducts(filter="All"){grid.innerHTML="";products.filter(p=>filter==="All"||p[2]===filter).forEach(p=>{const card=document.createElement("article");card.className="product-card";card.innerHTML=`<div class="product-image"><img loading="lazy" src="assets/products/${p[0]}.jpg" alt="${p[1]} — Young Gentleman"><div class="product-overlay"><span class="view-chip">Quick view</span></div></div><div class="product-meta"><div class="product-name">${p[1]}</div><div class="product-sub"><span>${p[2]}</span><span>${p[3]}</span></div></div>`;card.addEventListener("click",()=>openModal(p));grid.appendChild(card)})}
function openModal(p){modalImage.src=`assets/products/${p[0]}.jpg`;modalImage.alt=p[1];modalTitle.textContent=p[1];modalCategory.textContent=p[2]+" · Ages 4–15";modalPrice.textContent=p[3]+" indicative retail band";modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.body.style.overflow="hidden"}
function closeModal(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true");document.body.style.overflow=""}
document.querySelectorAll(".filter").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".filter").forEach(b=>b.classList.remove("active"));btn.classList.add("active");renderProducts(btn.dataset.filter)}));
document.querySelector(".modal-close").addEventListener("click",closeModal);document.querySelector(".modal-backdrop").addEventListener("click",closeModal);document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
const menu=document.querySelector(".menu-toggle"),nav=document.getElementById("nav");menu.addEventListener("click",()=>{const isOpen=nav.classList.toggle("open");menu.setAttribute("aria-expanded",isOpen)});document.querySelectorAll(".nav a").forEach(a=>a.addEventListener("click",()=>nav.classList.remove("open")));
document.querySelector(".enquiry-form").addEventListener("submit",e=>{e.preventDefault();const form=new FormData(e.currentTarget);if(BUYER_EMAIL.includes("REPLACE_WITH")){alert("Please add the Young Gentleman buyer email in script.js first. The site is otherwise ready to publish.");return}const subject=encodeURIComponent(`Young Gentleman Buyer Enquiry — ${form.get("company")}`),body=encodeURIComponent(`Hello Young Gentleman,\n\nName: ${form.get("name")}\nCompany / Store: ${form.get("company")}\nEmail: ${form.get("email")}\n\nEnquiry:\n${form.get("message")}\n\nRegards,\n${form.get("name")}`);window.location.href=`mailto:${BUYER_EMAIL}?subject=${subject}&body=${body}`});
document.querySelectorAll(".modal-enquire").forEach(a=>a.addEventListener("click",closeModal));renderProducts();